#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE_SOURCE_TYPE="$2"
STDIN=$(cat)

if [[ "$IMAGE_SOURCE_TYPE" == "dockerfile" ]] && [[ "$0" == *build ]]; then
  echo -n "$STDIN"
else
  STDIN=$(cat)
  HOSTNAME=$(hostname)
  echo -n "$STDIN --hostname=${HOSTNAME}"
fi
