#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE_SOURCE_TYPE="$2"
STDIN=$(cat)

if [[ "$IMAGE_SOURCE_TYPE" == "dockerfile" ]] && [[ "$0" == *build ]]; then
  echo -n "$STDIN"
else
  STDIN=$(cat)
  OPSWORKS_STACK_NAME=$(grep "OpsWorks Stack:" /etc/motd 2>/dev/null || true)
  if [[ -n "$OPSWORKS_STACK_NAME" ]]; then
    HOSTNAME=$(echo "$OPSWORKS_STACK_NAME" "$(hostname)" | awk -F: '{ print $2 }' | xargs | tr '[:upper:]' '[:lower:]' | sed -e 's: :-:g')
  else
    HOSTNAME=$(hostname)
  fi
  echo -n "$STDIN --hostname=${HOSTNAME}"
fi
